// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqUxf5wuseD5yjhr1AVTWgpK7yS8LvV6A',
    appId: '1:81488993802:web:42d638ca634559a8e2c9f3',
    messagingSenderId: '81488993802',
    projectId: 'odas-trl-framework',
    authDomain: 'odas-trl-framework.firebaseapp.com',
    storageBucket: 'odas-trl-framework.appspot.com',
    measurementId: 'G-K2DDXYD7VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANsCacH2JM3M7Jxxf0-8A_36fgXSwomCQ',
    appId: '1:81488993802:android:b4ba939c6606fa9fe2c9f3',
    messagingSenderId: '81488993802',
    projectId: 'odas-trl-framework',
    storageBucket: 'odas-trl-framework.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRrsYEPnGGCec7Juk_86NR-5bTi8quuOA',
    appId: '1:81488993802:ios:1bfdfede16e4a64ae2c9f3',
    messagingSenderId: '81488993802',
    projectId: 'odas-trl-framework',
    storageBucket: 'odas-trl-framework.appspot.com',
    iosClientId: '81488993802-mtm3u77l5s35hq19n4e5o8nnqb40utf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.odasTrlFramework',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRrsYEPnGGCec7Juk_86NR-5bTi8quuOA',
    appId: '1:81488993802:ios:1bfdfede16e4a64ae2c9f3',
    messagingSenderId: '81488993802',
    projectId: 'odas-trl-framework',
    storageBucket: 'odas-trl-framework.appspot.com',
    iosClientId: '81488993802-mtm3u77l5s35hq19n4e5o8nnqb40utf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.odasTrlFramework',
  );
}
